######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 4 02:03:53 2014
######################################################################

TEMPLATE = app
TARGET = 
QT += core gui
QT += widgets
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
